### ISSUE TITLE
Cannot setup: is the example wrong?

### ISSUE THREAD

**Issue by martinsantibanez** [jasancheg/react-native-svgx#2]
Hey!
first, thanks for this package.
I'm trying to use it. I successfully converted my files into json using [react-native-prepare-svg](https://github.com/jasancheg/react-native-prepare-svg), however, when trying to use the generated file with this package I'm getting the following error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at Svgx.js:57.
    in Svgx (at SingleTrip.js:47)
...
```
this lane makes reference to:
```
    return (
>      <Node {...currentAttrs} key={i}>
        {child.childs && child.childs.length ? renderSvgChilds(Svg, child.childs, styles) : null}
      </Node>
    );
```
and the way I'm using it is:
```
import { Svg } from 'react-native-svg';
import { Svgx } from 'react-native-svgx'
import * as companies from '../../../assets/svg/companies.json';
...

<Svgx {... { component: Svg, data: companies[companyLogo], styles: styles.companyImage }} />
```
also tried:
```
<Svgx key={logoKey} component={Svg} data={companies[companyLogo]} styles={styles.companyImage}  />
```
I saw that in the example you import the library as `import { Svgx } from 'svgx';`, however my guess was that this is a mistake and it should be `import { Svgx } from 'react-native-svgx'`
Is this correct? or do I need Svgx as well?

Do you have any clue of what could be failing? or it might be because of my react version? (as the package was updated 1 year ago)

Thanks!

**Comment by jasancheg** [comment]
@mertinop  Please sorry, let me check tomorrow, the package must be very discontinued.

**Comment by martinsantibanez** [comment]
@jasancheg no worries, I can tell. I have a folder of svg files, and I want to output the corresponding one depending on what I get from the backend (`companyLogo` in my example). As [dynamic imports are not possible in react-native because of metro bundler](https://github.com/facebook/react-native/issues/6391), my approach was to use this package and get the data from the json.
At this point, after hours trying I'm seriously considering switching to webpack using [haul](https://github.com/callstack/haul) :(

Gracias
